name: 漏洞反馈 - 简体中文
description: 提交漏洞反馈来帮助我们进行修复
title: "[Bug]: "
labels: ["type: bug"]
body:
  - type: textarea
    attributes:
      label: Bug
      description: 简述这个漏洞
    validations:
      required: true

  - type: textarea
    attributes:
      label: 复现方案
      description: 请描述复现此漏洞的步骤
    validations:
      required: true

  - type: textarea
    attributes:
      label: 预期行为
      description: 请简述预期的行为。
    validations:
      required: true

  - type: input
    attributes:
      label: Glacie版本
      description: 你所使用的 Glacie 的版本
    validations:
      required: true

  - type: input
    attributes:
      label: 加载器版本
      description: 你使用的Mod加载器和版本（例如LeviLamina v0.8.0、Endstone v0.5.0）
    validations:
      required: true

  - type: textarea
    attributes:
      label: 更多信息
      description: 如果有更多信息，例如截图，日志等等，请尽可能提供。
